---
network:
  plugin: flannel
  options:
    flannel_image: quay.io/coreos/flannel:v0.9.1
    flannel_cni_image: quay.io/coreos/flannel-cni:v0.2.0

auth:
  strategy: x509
  options:
    foo: bar

nodes:
  - address: ec2-52-59-241-103.eu-central-1.compute.amazonaws.com
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: ./ssh_keys/id_rsa
    internal_address: 10.0.101.154
  - address: ec2-18-195-216-98.eu-central-1.compute.amazonaws.com
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: ./ssh_keys/id_rsa
    internal_address: 10.0.101.121
  - address: ec2-18-196-23-176.eu-central-1.compute.amazonaws.com
    user: ubuntu
    role: [controlplane,worker,etcd]
    ssh_key_path: ./ssh_keys/id_rsa
    internal_address: 10.0.101.181
  
    
services:
  etcd:
    image: quay.io/coreos/etcd:latest
  kube-api:
    image: rancher/k8s:v1.8.3-rancher2
  kube-controller:
    image: rancher/k8s:v1.8.3-rancher2
  scheduler:
    image: rancher/k8s:v1.8.3-rancher2
  kubelet:
    image: rancher/k8s:v1.8.3-rancher2
  kubeproxy:
    image: rancher/k8s:v1.8.3-rancher2


